spring.datasource.url=postgresql://mysqldb_gh0s_user:ggRB9eFqAvq9t421z3PvA1DfNtgXnM3k@dpg-d6kjus15pdvs7382p3u0-a/mysqldb_gh0s
spring.datasource.username=mysqldb_gh0s_user
spring.datasource.password=ggRB9eFqAvq9t421z3PvA1DfNtgXnM3k
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true